# Time the bot must relocate the ships to farm
refresh_ships: 25

# Number of ships you want to farm
n_ships_to_fight: 10

# Minimum number to start a battle
n_minimum_ships_to_fight: 10

# Percentage at which ships return
# Accepted values: 50, 75 e 100
ship_work_percent: 50

# ---------------------------------------------------------
telegram:
  # Settings for telegram integration 
  token: ""
  chat_id: 0

  # Timer when your chest image is sent to telegram
  refresh_print_token: 60
# ---------------------------------------------------------

# ---------------------------------------------------------
screen:
  scroll:
    # Total number of times the screen scrolls down
    # Every 10 ships, use 3 scrolls. 
    # Example: 
    # if u have 10 spaceships: 4 // if u have 20 spaceships: 8 // if u have 30 spaceships: 12 // ETC
    repeat: 8

    # Distance when scrolling down
    distance: -175

    # Duration of scrolling
    duration: 2 

    # Wait time to stop scrolling before checking the heroes on the screen.
    wait: 1
  
  # Number of login attempts
  number_login_attempts: 3

  # Timer to check popup screen errors, if it's in error, restarts with login again
  refresh_check_error: 5
# ---------------------------------------------------------

# ---------------------------------------------------------
generals:
  # Save all logs in file logs/logger.txt
  #   0: Don't save log
  #   1: Save log
  save_log_file: 0
  
  # Reset log file on start
  #   0: false
  #   1: true
  reset_log_file: 1

  # Which hotkey is used to refresh the browser
  #   1: CTRL + F5
  #   2: CTRL + SHIFT + R
  refresh_page_shortcut: 1
# ---------------------------------------------------------
  

# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# DONT CHANGE THIS CONFIGS
# ------------------------
threshold:
  default: 0.8
  to_work: 0.8
# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
